
version: '3.1'
services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: vishal
      MONGO_INITDB_ROOT_PASSWORD: 65072d0281127af6a924e65d

  backend:
    build: ./backend
    restart: on-failure
 
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/backend/node_modules
    depends_on:
      - "mongo"

  frontend:
    build: ./client
    restart: on-failure
    ports:
     - 3001:80
    volumes:
     - ./:/app
     - /app/client/node_modules
    
