version: '3.1'
services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: vishal
      MONGO_INITDB_ROOT_PASSWORD: 65072d0281127af6a924e65d
    volumes:
      - ./backup:/backup
      - ./mongo_data:/data/db
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: vishu7im/almanilokheri-backend:latest 
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - "mongo"
    environment:
      NODE_ENV: production
    volumes:
      - /etc/letsencrypt/live/almanilokheri.in/fullchain.pem:/etc/letsencrypt/live/almanilokheri.in/fullchain.pem
      - /etc/letsencrypt/live/almanilokheri.in/privkey.pem:/etc/letsencrypt/live/almanilokheri.in/privkey.pem
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: vishu7im/almanilokheri-frontend:latest 
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/almanilokheri.in/fullchain.pem:/etc/letsencrypt/live/almanilokheri.in/fullchain.pem
      - /etc/letsencrypt/live/almanilokheri.in/privkey.pem:/etc/letsencrypt/live/almanilokheri.in/privkey.pem
    
    logging:
      options:
        max-size: "10m"
        max-file: "3"
