name: Deploy alma-nilokheri

on:
  push:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables for Frontend
        run: |
          echo "All variables : ${{ secrets }}"
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_PRIVET_KEY: ${{ secrets.REACT_APP_PRIVET_KEY }}
          REACT_APP_AWS_Access_key: ${{ secrets.REACT_APP_AWS_ACCESS_KEY }}
          REACT_APP_AWS_secret_key: ${{ secrets.REACT_APP_AWS_SECRET_KEY }}
          REACT_APP_AWS_S3_BUCKET: ${{ secrets.REACT_APP_AWS_S3_BUCKET }}
          REACT_APP_AWS_REGION: ${{ secrets.REACT_APP_AWS_REGION }}
          REACT_APP_apiKey: ${{ secrets.REACT_APP_APIKEY }}
          REACT_APP_authDomain: ${{ secrets.REACT_APP_AUTHDOMAIN }}
          REACT_APP_projectId: ${{ secrets.REACT_APP_PROJECTID }}
          REACT_APP_storageBucket: ${{ secrets.REACT_APP_STORAGEBUCKET }}
          REACT_APP_messagingSenderId: ${{ secrets.REACT_APP_MESSAGINGSENDERID }}
          REACT_APP_appId: ${{ secrets.REACT_APP_APPID }}
          REACT_APP_measurementId: ${{ secrets.REACT_APP_MEASUREMENTID }}
          REACT_APP_TRACKING_ID: ${{ secrets.REACT_APP_TRACKING_ID }}
          REACT_APP_Month: ${{ secrets.REACT_APP_MONTH }}
          REACT_APP_Year: ${{ secrets.REACT_APP_YEAR }}

      - name: Install Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Navigate to client directory and  Install dependencies and  Build React app
        run: |
          cd ./client
          npm install
          npm run build
        env:
          CI: false

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_KEY}}

      - name: Build frontend Docker Image
        run: docker build -t vishu7im/almanilokheri-frontend ./client

      - name: Publish frontend image to Docker Hub
        run: docker push vishu7im/almanilokheri-frontend:latest

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables for Backend
        run: |
          echo "All variables : ${{ secrets }}"
        env:
          DATABASE_KEY: ${{ secrets.DATABASE_KEY }}
          privateKey: ${{ secrets.PRIVATEKEY }}
          sender_mail: ${{ secrets.SENDER_MAIL }}
          mail_pwd: ${{ secrets.MAIL_PWD }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_KEY}}

      - name: Build Backend Docker Image
        run: docker build -t vishu7im/almanilokheri-backend ./backend

      - name: Publish Backend image to Docker Hub
        run: docker push vishu7im/almanilokheri-backend:latest

  deploy:
    runs-on: self-hosted
    needs:
      - backend
      - frontend
    steps:
      - name: Deploy to production
        run: |
          docker-compose pull
          docker-compose up -d
      - name: DONE
        run: echo "Deployment complete"
