name: Deploy alma-nilokheri

on:
  push:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment variables
        env:
          DATABASE_KEY: ${{ secrets.DATABASE_KEY }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          apiKey: ${{ secrets.API_KEY }}
          authDomain: ${{ secrets.AUTH_DOMAIN }}
          projectId: ${{ secrets.PROJECT_ID }}
          storageBucket: ${{ secrets.STORAGE_BUCKET }}
          messagingSenderId: ${{ secrets.MESSAGING_SENDER_ID }}
          appId: ${{ secrets.APP_ID }}
          private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_x509_cert_url: ${{ secrets.CLIENT_X509_CERT_URL }}
          sender_mail: ${{ secrets.SENDER_MAIL }}
          mail_pwd: ${{ secrets.MAIL_PWD }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_KEY}}
      - name: Build Backend Docker Image
        run: docker build -t vishu7im/alma-nilokheri-backend ./backend
      - name: Publish Backend image to Docker Hub
        run: docker push vishu7im/alma-nilokheri-backend

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy .env file
        run: cp /home/vishu7im/Tech/GBN/client/.env client/.env
      - name: Navigate to client directory
        run: cd client
      - name: Install Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: vishu7im/alma-nilokheri-frontend:latest

  deploy:
    runs-on: self-hosted
    needs:
      - backend
      - frontend
    steps:
      - name: Deploy to production
        run: docker-compose -f docker-compose.yml up -d --build
      - name: DONE
        run: echo "deployment complete"
